<a href="https://colab.research.google.com/github/lara-ms/Aula-C11B/blob/main/Cap4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução ao Numpy


---



Objetivos:
- Conhecer recursos essenciais do
pacote mais fundamental para Ciência
de Dados em Python, o NumPy

- Explorar suas funções mais populares
e recursos de álgebra linear, como o
NumPy Array de 1 e 2 dimensões

- Começar a realizar o carregamento e
tratamento de Datasets por meio
desta biblioteca


Destaques desta biblioteca :

- Manipulação de arrays multidimentsionais como vetores
e
matrizes

- Grande variedade de operações matemáticas disponíveis • Preparada para lidar com grandes quantidades de dados
(Sua base
é criada na linguagem C)

- Biblioteca mãe de outras, como Pandas
e MatplotLib

## Numpy Arrays

Para usar o **NdArray** pode criar **tuplas e listas** para usar no numpy.

O NumPy Array guarda apenas elementos do mesmo tipo
• Isso fornece maior desempenho nas operações
• Menor uso de memóri

In [ ]:
# Importando o numpy
import numpy as np

In [ ]:
# Criando um numpy array
arr = np.array([21, 20, 49, 17])

print(arr)

print(type(arr))


[21 20 49 17]
<class 'numpy.ndarray'>


Propriedades do Array

In [ ]:

print(arr.size)  # numero de elementos

print(arr.ndim)  # dimensao

print(arr.shape) # formato

4
1
(4,)


In [ ]:
mtz = np.array([[10, 20, 30],[11, 21, 31],[12, 22, 32],[13,  23, 33]])

print(mtz)

print(type(mtz))



[[10 20 30]
 [11 21 31]
 [12 22 32]
 [13 23 33]]
<class 'numpy.ndarray'>


Propriedades de Matriz (Array de 2 dimensões)  

In [ ]:

print(mtz.size)  # numero de elementos

print(mtz.ndim)  # dimensao

print(mtz.shape) # formato

12
2
(4, 3)


## Funções pré prontas para estruturas de Numpy Arrays

In [ ]:
# Ones
mtz = np.ones([5,5])
print(mtz)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Zeros
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Transformando uum Array em Matriz
print(arr.reshape(5,2))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# Arange
mtz = np.arange(2, 21, 2).reshape(2, 5)

print(mtz)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


## Operações entre Numpy Arrays

In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
arr3 = arr1 + arr2

print(arr3)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

# BROADCASTING - qnd um ESCALAR faz uma operacao com um ARRAY
print(5 * arr3)

# Concatenar Arrays
arr3 = np.concatenate([arr1, arr2])
print(arr3)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 55 110 165 220]
[10 20 30 40  1  2  3  4]


In [ ]:
# Estruturando uma matriz com contas
mtz = np.arange(10, 96, 5).reshape(3, 6)

print(mtz)

# Extraindo a soma da coluna 1
print(mtz.sum(axis=0)[0]) # eixo 0 = coluna

print(mtz.sum(axis=1)[1]) # eixo 1 = linha


[[10 15 20 25 30 35]
 [40 45 50 55 60 65]
 [70 75 80 85 90 95]]
120
315


Numeros aleatorios em Numpy

In [ ]:
arr = np.random.randint(10)
print(arr)

5


In [ ]:
np.random.seed(5) # platando a semente aleatoria
arr = np.random.randint(1, 10, 10)
print(arr)


[4 7 7 1 9 5 8 1 1 8]


In [ ]:
# Extraindo elementos unicos
print(np.unique(arr))

# Contando elemelementos unicos
print(np.unique(arr, return_counts=True))

[1 4 5 7 8 9]
(array([1, 4, 5, 7, 8, 9]), array([3, 1, 1, 2, 2, 1]))
