<a href="https://colab.research.google.com/github/lara-ms/Aula-C11B/blob/main/Cap4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução ao Numpy


---



Objetivos:
- Conhecer recursos essenciais do
pacote mais fundamental para Ciência
de Dados em Python, o NumPy

- Explorar suas funções mais populares
e recursos de álgebra linear, como o
NumPy Array de 1 e 2 dimensões

- Começar a realizar o carregamento e
tratamento de Datasets por meio
desta biblioteca


Destaques desta biblioteca :

- Manipulação de arrays multidimentsionais como vetores
e
matrizes

- Grande variedade de operações matemáticas disponíveis • Preparada para lidar com grandes quantidades de dados
(Sua base
é criada na linguagem C)

- Biblioteca mãe de outras, como Pandas
e MatplotLib

## Numpy Arrays

Para usar o **NdArray** pode criar **tuplas e listas** para usar no numpy.

O NumPy Array guarda apenas elementos do mesmo tipo
• Isso fornece maior desempenho nas operações
• Menor uso de memóri

In [ ]:
# Importando o numpy
import numpy as np

In [ ]:
# Criando um numpy array
arr = np.array([21, 20, 49, 17])

print(arr)

print(type(arr))


[21 20 49 17]
<class 'numpy.ndarray'>


Propriedades do Array

In [ ]:

print(arr.size)  # numero de elementos

print(arr.ndim)  # dimensao

print(arr.shape) # formato

4
1
(4,)


In [ ]:
mtz = np.array([[10, 20, 30],[11, 21, 31],[12, 22, 32],[13,  23, 33]])

print(mtz)

print(type(mtz))



[[10 20 30]
 [11 21 31]
 [12 22 32]
 [13 23 33]]
<class 'numpy.ndarray'>


Propriedades de Matriz (Array de 2 dimensões)  

In [ ]:

print(mtz.size)  # numero de elementos

print(mtz.ndim)  # dimensao

print(mtz.shape) # formato

12
2
(4, 3)


## Funções pré prontas para estruturas de Numpy Arrays

In [ ]:
# Ones
mtz = np.ones([5,5])
print(mtz)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Zeros
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Transformando uum Array em Matriz
print(arr.reshape(5,2))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# Arange
mtz = np.arange(2, 21, 2).reshape(2, 5)

print(mtz)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


## Operações entre Numpy Arrays

In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
arr3 = arr1 + arr2

print(arr3)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

# BROADCASTING - qnd um ESCALAR faz uma operacao com um ARRAY
print(5 * arr3)

# Concatenar Arrays
arr3 = np.concatenate([arr1, arr2])
print(arr3)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 55 110 165 220]
[10 20 30 40  1  2  3  4]


In [ ]:
# Estruturando uma matriz com contas
mtz = np.arange(10, 96, 5).reshape(3, 6)

print(mtz)

# Extraindo a soma da coluna 1
print(mtz.sum(axis=0)[0]) # eixo 0 = coluna

print(mtz.sum(axis=1)[1]) # eixo 1 = linha


[[10 15 20 25 30 35]
 [40 45 50 55 60 65]
 [70 75 80 85 90 95]]
120
315


Numeros aleatorios em Numpy

In [ ]:
arr = np.random.randint(10)
print(arr)

5


In [ ]:
np.random.seed(5) # platando a semente aleatoria
arr = np.random.randint(1, 10, 10)
print(arr)


[4 7 7 1 9 5 8 1 1 8]


In [ ]:
# Extraindo elementos unicos
print(np.unique(arr))

# Contando elemelementos unicos
print(np.unique(arr, return_counts=True))

[1 4 5 7 8 9]
(array([1, 4, 5, 7, 8, 9]), array([3, 1, 1, 2, 2, 1]))


## Slicing no NumPy

In [ ]:
import numpy as np

In [ ]:
# Plantando a mesma semente aleatoria
np.random.seed(10)

# Estruturando a matmatriz 3x3
mtz = np.random.randint(1, 99, 9).reshape(3,3)

print(mtz)

[[10 16 65]
 [29 90 94]
 [30  9 74]]


In [ ]:
# Extraindo apenas a segunda linha da matriz
print(mtz[1])
print("--------------------------")

# Extraindo apenas a terceira coluna da matriz
print(mtz[:,2])
print("--------------------------")

# Extraindo a matriz 2x2 no canto inferior direito da matriz
print(mtz[1:,1:])

[29 90 94]
--------------------------
[65 94 74]
--------------------------
[[90 94]
 [ 9 74]]


## Condicionais no NumPy

voce mata as estruturas de repeticao de programacao   

In [ ]:
print(mtz)
print("--------------------------")

# Mostre apenas os elementos menores que 70
print(mtz < 70)

print(mtz[mtz < 70])
print("--------------------------")

# Retorne apenas os numeros pares
print(mtz[mtz % 2 == 0])

[[10 16 65]
 [29 90 94]
 [30  9 74]]
--------------------------
[[ True  True  True]
 [ True False False]
 [ True  True False]]
[10 16 65 29 30  9]
--------------------------
[10 16 90 94 30 74]


## Analise de Padroes textuais com NumPy

In [ ]:
arr = np.array(['Inatel', 'Casa Viva', 'ICC',
                'CDG', 'eHealth', 'CSILab',
                'RobotBulls', 'ProdLab', 'CRA',
                'CRR', 'Ave'])

print(arr)

['Inatel' 'Casa Viva' 'ICC' 'CDG' 'eHealth' 'CSILab' 'RobotBulls'
 'ProdLab' 'CRA' 'CRR' 'Ave']


### Char

In [ ]:
# Buscando qual texto aceita um padrao informado
print(np.char.find(arr, 'a'))
print("--------------------------")

print(np.char.find(arr, 'a') >= 0)
print("--------------------------")

print(arr[np.char.find(arr, 'a') >= 0])
print("--------------------------")

# Padronizando para maiusculo (upper) ou minusculo (lower)
arr = np.char.upper(arr)
print(arr[np.char.find(arr, 'A') >= 0])


[ 2  1 -1 -1  3  4 -1  5 -1 -1 -1]
--------------------------
[ True  True False False  True  True False  True False False False]
--------------------------
['Inatel' 'Casa Viva' 'eHealth' 'CSILab' 'ProdLab']
--------------------------
['INATEL' 'CASA VIVA' 'EHEALTH' 'CSILAB' 'PRODLAB' 'CRA' 'AVE']


## Importando Dataset no Numpy

No colab deve sempre colocar dnv o dataset em arquivos pq sempre vai apagar

In [ ]:
dataset = np.loadtxt('space.csv', delimiter = ';', dtype = str)

print(dataset)

[['\ufeffNum' 'Company Name' 'Location' ... 'Status Rocket' ' Cost'
  'Status Mission']
 ['0' 'SpaceX' 'LC-39A Kennedy Space Center Florida USA' ...
  'StatusActive' '50.0 ' 'Success']
 ['1' 'CASC' 'Site 9401 (SLS-2) Jiuquan Satellite Launch Center China'
  ... 'StatusActive' '29.75 ' 'Success']
 ...
 ['4321' 'US Navy' 'LC-18A Cape Canaveral AFS Florida USA' ...
  'StatusRetired' '0' 'Failure']
 ['4322' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']
 ['4323' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']]


In [ ]:
# Extraindo as colunas do dataset
print(dataset[0,:])
print("-------------------------------------------------------")

# Extraindo o nome das empresas
print(dataset[1:,1]) # Tirando o nome da coluna com '1:'

# Extraindo os nomes unicos, para nao aparecer nomes repetidos
print(np.unique(dataset[1:,1]))
print("-------------------------------------------------------")

print(np.unique(dataset[1:,1], return_counts=True))

['\ufeffNum' 'Company Name' 'Location' 'Datum' 'Detail' 'Status Rocket'
 ' Cost' 'Status Mission']
-------------------------------------------------------
['SpaceX' 'CASC' 'SpaceX' ... 'US Navy' 'RVSN USSR' 'RVSN USSR']
['AEB' 'AMBA' 'ASI' 'Arianespace' "Arm??e de l'Air" 'Blue Origin' 'Boeing'
 'CASC' 'CASIC' 'CECLES' 'CNES' 'Douglas' 'EER' 'ESA' 'Eurockot' 'ExPace'
 'Exos' 'General Dynamics' 'IAI' 'ILS' 'IRGC' 'ISA' 'ISAS' 'ISRO' 'JAXA'
 'KARI' 'KCST' 'Khrunichev' 'Kosmotras' 'Land Launch' 'Landspace'
 'Lockheed' 'MHI' 'MITT' 'Martin Marietta' 'NASA' 'Northrop' 'OKB-586'
 'OneSpace' 'RAE' 'RVSN USSR' 'Rocket Lab' 'Roscosmos' 'SRC' 'Sandia'
 'Sea Launch' 'SpaceX' 'Starsem' 'ULA' 'US Air Force' 'US Navy' 'UT'
 'VKS RF' 'Virgin Orbit' 'Yuzhmash' 'i-Space']
-------------------------------------------------------
(array(['AEB', 'AMBA', 'ASI', 'Arianespace', "Arm??e de l'Air",
       'Blue Origin', 'Boeing', 'CASC', 'CASIC', 'CECLES', 'CNES',
       'Douglas', 'EER', 'ESA', 'Eurockot', 'ExP