<a href="https://colab.research.google.com/github/lara-ms/Aula-C11B/blob/main/Cap4_Exercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercicios Numpy

---



## EXERCÍCIOS (PARTE 1)

1. Crie dois NumPy Arrays unidimensionais de tamanho 8 : um formado apenas por 1’s e outro formado por números aleatórios entre 0 e 9. Some estes dois NumPy Arrays e guarde o resultado dentro de um terceiro NumPy Array. Por fim, faça o seguinte :

- Se a soma de todos os elementos do Array resultante for >= 40, remodele este NumPy Array para se tornar uma matriz com mais linhas do que colunas. Senão, remodele para que se torne uma matriz com mais colunas do que linhas.

In [1]:
import numpy as np

In [9]:
# Gera array so de 1's de tamanho 8
arr1 = np.ones(8)
# Gera array de 0 a 10 de tamanho 8
arr2 = np.random.randint(0, 10, 8)

print("arr1: ")
print(arr1)

print("\narr2: ")
print(arr2)

# Soma os dois arrays
arr3 = arr1 + arr2

print("\narr3: ")
print(arr3)

arr1: 
[1. 1. 1. 1. 1. 1. 1. 1.]

arr2: 
[1 8 1 1 5 7 2 3]

arr3: 
[2. 9. 2. 2. 6. 8. 3. 4.]


In [10]:
print("Soma dos elementos do arr3: ", arr3.sum())

Soma dos elementos do arr3:  36.0


2. Crie dois NumPy Arrays unidimensionais: um de números pares de 0 à 51 e outro também de números pares de 100 até 50. Em seguida, os concatene e mostre os resultados ordenados

In [11]:
arr1 = np.arange(0, 52, 2)
arr2 = np.arange(100, 50, -2)

print("arr1: ")
print(arr1)

print("\narr2: ")
print(arr2)

arr1: 
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]

arr2: 
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52]


In [12]:
arr3 = np.concatenate((arr1, arr2))

print(np.sort(arr3))

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


3. Mini Campo Minado

- Crie um NumPy Array 2x2 formado apenas por 0’s

- Em seguida, adicione um número 1 em uma posição aleatória desta matriz;

- Faça uma entrada de dados para solicitar o usuário que faça uma jogada (selecione uma posição da matriz)

- I. Se ele selecionar todas as posições em que o número 1 não se encontra, mostre a mensagem “Congratulations! You beat the game!:)”

- II. Senão, se dentro das 3 primeiras jogadas ele achar o número 1, mostre a mensagem “Game Over!:( Try Again!”

In [19]:
# Gerando matriz 2x2 todos elementos 0's
mtz = np.zeros((2,2))

# Sorteando uma linha e coluna
linha = np.random.randint(0, 2)
coluna = np.random.randint(0, 2)

# Colocando um 1 na posição sorteada
mtz[linha, coluna] = 1

print(mtz) # Para testar a celula abaixo

[[0. 1.]
 [0. 0.]]


In [18]:
# Contador auxiliar para saber se a pessoa nao errou nada
cont = 0

for i in range(3):
  linha = int(input("\nDigite a linha: "))
  coluna = int(input("Digite a coluna: "))

  if mtz[linha, coluna] == 1:
    print("\nGame Over!:( Try Again!")
    break
  else:
    # Somando 1 para cada acerto
    cont+=1

# Se acertar 3 sem acertar o 1 mostra mensagem
if cont == 3:
  print("\nCongratulations! You beat the game!:)")


Digite a linha: 0
Digite a coluna: 0

Digite a linha: 1
Digite a coluna: 0

Digite a linha: 1
Digite a coluna: 1

Congratulations! You beat the game!:)


## EXERCÍCIOS (PARTE 2)

4. Crie uma matriz de tamanho qualquer. Extraia seu número de linhas e colunas, multiplique-os, e diga se esta matriz poderia se tornar um vetor unidimensional com número par ou ímpar de elementos

In [37]:
linha = np.random.randint(0, 6)
coluna = np.random.randint(0, 6)

arr = np.random.randint(1, 51, linha*coluna)

mtz = arr.reshape(linha, coluna)

print(mtz)

[[26 14 29 23 31]
 [31 26 13  2 32]
 [37 28 19 30 14]
 [23 24 31 12 29]
 [11 25 10 16 19]]


In [38]:
quant_col = mtz.shape[1]
quant_lin = mtz.shape[0]

print("Quantidade de colunas: ", quant_col)
print("Quantidade de linhas: ", quant_lin)
print("Quantidade de elementos: ", quant_col*quant_lin)

if quant_col*quant_lin % 2 == 0:
  print("\nPode virar vetor unidimensional com numero PAR de elementos")
else:
  print("\nPode virar vetor unidimensional com numero IMPAR de elementos")

Quantidade de colunas:  5
Quantidade de linhas:  5
Quantidade de elementos:  25

Pode virar vetor unidimensional com numero IMPAR de elementos


5. Crie uma matriz de tamanho 4x4 formada por números aleatórios inteiros entre 1 e 50 (use seed = 10 antes)

- Mostre o resultado da média de cada linha e cada coluna da matriz gerada

- Apresente o maior valor das médias das linhas e também das colunas

- Mostre a quantidade de aparições de cada um dos números gerados na
matriz. Em seguida, mostre apenas os números que aparecem 2 vezes

In [52]:
np.random.seed(10)

arr = np.random.randint(1, 51, 16)
mtz = arr.reshape(4, 4)

print(mtz)

# Media de cada linha e maior valor
print("\nMedia de cada linha: ")
print(mtz.sum(axis=1)/4)
print("Maior valor: ")
print((mtz.sum(axis=1)/4).max())

# Media de cada coluna e maior valor
print("\nMedia de cada coluna: ")
print(mtz.sum(axis=0)/4)
print("Maior valor: ")
print((mtz.sum(axis=0)/4).max())

# Quantidade de apariçõe de cada numero
print("\nQuantidade de aparições de cada numero: ")
aparicoes = np.unique(mtz, return_counts = True)
print(aparicoes)

# Aparecem 2 vezes
print("\nAparecem 2 vezes: ")
for i in range(len(np.unique(mtz))):
  if aparicoes[1][i] == 2:
    print(aparicoes[0][i])

[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]

Media de cada linha: 
[16.   33.75 34.5  23.75]
Maior valor: 
34.5

Media de cada coluna: 
[29.75 24.25 33.75 20.25]
Maior valor: 
33.75

Quantidade de aparições de cada numero: 
(array([ 1,  9, 10, 16, 26, 29, 30, 37, 41, 43, 49, 50]), array([2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2]))

Aparecem 2 vezes: 
1
10
30
50
