<a href="https://colab.research.google.com/github/lara-ms/Aula-C11B/blob/main/Cap5_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas


---



In [2]:
import numpy as np
import pandas as pd

## Pandas Series (1-D)

### Como preencher uma Series

In [4]:
# Lista de labels
labels = ['Tiago', 'Mateus', 'Bruna', 'Julia']

# Lista de valores
valores = [23, 25, 27, 22]

### Criando a Series

In [5]:
se1 = pd.Series(index=labels, data=valores)

print(se1)

print(type(se1))

Tiago     23
Mateus    25
Bruna     27
Julia     22
dtype: int64
<class 'pandas.core.series.Series'>


### Acessando os valores da Series

In [6]:
print(se1['Mateus'])

print(se1[['Mateus', 'Julia']])

25
Mateus    25
Julia     22
dtype: int64


### Operações de Series

In [12]:
s1 = pd.Series({'v1' : 10,'v2' : 45,'v3' : 70})
s2 = pd.Series({'v1' : 10,'v4' : 50,'v3' : 70})

print(s1)
print("\n")

print(s2)
print('\n')

print(s1 + s2)
print('\n')

print(s1.add(s2, fill_value=0))

v1    10
v2    45
v3    70
dtype: int64


v1    10
v4    50
v3    70
dtype: int64


v1     20.0
v2      NaN
v3    140.0
v4      NaN
dtype: float64


v1     20.0
v2     45.0
v3    140.0
v4     50.0
dtype: float64


## Pandas Dataframe (2-D)

### Como preencher DataFrame

In [15]:
# Lista de labels (COLUNAS)
colunas = ['W', 'X', 'Y', 'Z']

# Lista de labels (LINHAS)
linhas = ['A', 'B', 'C', 'D', 'E']

# Lista de valores
np.random.seed(10)
valores = np.random.randint(1, 50, [5, 4])
print(valores)


[[10 37 16  1]
 [29 26 30 49]
 [30  9 10  1]
 [43 41 37 17]
 [37 48 12 25]]


### Criando DataFrame

In [16]:
df = pd.DataFrame(columns = colunas,
                  index = linhas,
                  data = valores)

print(df)

    W   X   Y   Z
A  10  37  16   1
B  29  26  30  49
C  30   9  10   1
D  43  41  37  17
E  37  48  12  25


### Manipulando DataFrame

In [20]:
# Puxando uma unica coluna
print(df['X'])
print(type(df['X']))
print("\n")

# Puxando mais de uma coluna
print(df[['Y', 'Z']])
print(type(df[['Y', 'Z']]))
print("\n")

# Puxando uma unica celula [COLUNA][LINHA]
print(df['Y']['C'])
print('\n')

# Puxando multiplas colunas
print(df[['W', 'X', 'Z']])
print('\n')



A    37
B    26
C     9
D    41
E    48
Name: X, dtype: int64
<class 'pandas.core.series.Series'>


    Y   Z
A  16   1
B  30  49
C  10   1
D  37  17
E  12  25
<class 'pandas.core.frame.DataFrame'>


10


    W   X   Z
A  10  37   1
B  29  26  49
C  30   9   1
D  43  41  17
E  37  48  25


### Slicing de dados no dataframe com LOC (Labels) e ILOC (Indices Numericos)


LOC

In [26]:
# Puxando uma unica linha
print(df.loc['C', ['W', 'X', 'Y', 'Z']])
print("\n")
print(df.loc['C'])
print('\n')

# Puxando mais de uma linha
print(df.loc[['B', 'E']])
print('\n')

# Puxando o quadrado do canto inferior direito
print(df.loc[['D','E'], ['Y', 'Z']])


W    30
X     9
Y    10
Z     1
Name: C, dtype: int64


W    30
X     9
Y    10
Z     1
Name: C, dtype: int64


    W   X   Y   Z
B  29  26  30  49
E  37  48  12  25


    Y   Z
D  37  17
E  12  25


ILOC

In [35]:
# Puxando uma unica linha
print(df.iloc[2, :]) # -> df.iloc[2]
print("\n")

# Puxando mais de uma linha
print(df.iloc[[1,4]])
print('\n')

# Puxando o quadrado do canto inferior direito
print(df.iloc[[3,4], [2,3]])

W    30
X     9
Y    10
Z     1
Name: C, dtype: int64


    W   X   Y   Z
B  29  26  30  49
E  37  48  12  25


    Y   Z
D  37  17
E  12  25
